### ISSUE TITLE
WidgetのViewがおかしいので修正する

### ISSUE THREAD

**Issue by naipaka** [naipaka/NextSunnyDay-iOS#63]
# 概要
- 晴れがなくても背景色がオレンジになってる
    - ViewModelのどっかがおかしそう
- 来週以降が右に寄りすぎ
    - View調整
- 地名入力済みかつエラーのとき、placeholderが表示されない
    - entity.cityName.isEmptyで判定しているため
        - entry.daily.isEmptyで判定する

<img src="https://user-images.githubusercontent.com/45661924/96887518-9ff6e900-14bf-11eb-9b02-64d268bf4076.png" width="320">

# 対応内容
- [x] 直す

**Comment by riscait** [comment]
グラデーションが綺麗✨

**Comment by naipaka** [comment]
わーい！ありがとうございます！☀️
