### ISSUE TITLE
GitHub ActionsのCI実行時間が長いので原因調査・改善する

### ISSUE THREAD

**Issue by naipaka** [naipaka/NextSunnyDay-iOS#67]
# 概要
CI実行時間が長いので調査・改善する。
だいたい13〜18分くらいかかってる。
SPM使ってるからそんなもんなのかな？

# 対応内容
- [ ] 調査
- [x] 改善
    - [x] Mintキャッシュ
    - [x] SwiftPMキャッシュ

**Comment by uhooi** [comment]
コメント失礼します！
GitHub Actionsのワークフローファイルを見て、私のを参考にしてくださっているのがわかってとても嬉しいです 😄 

Mintのキャッシュが取れていないのが原因で、それを直せば5分ほど短縮できそうです。
以下のようにしてMintで管理しているライブラリのバイナリを `mint` フォルダ以下に格納することで、解消できると思います。
https://github.com/uhooi/UhooiPicBook/blob/develop/.github/workflows/main.yml#L29-L31

**Comment by naipaka** [comment]
@uhooi 
コメントありがとうございます！！！
ウホーイさんのリポジトリのワークフローファイルを何度も見て参考にさせていただきました！🙇‍♂️
iOSDC2020でのハンズオン参加がGitHub Actionsを使ってみようと思ったきっかけになったので、とても感謝しています。

アドバイスを元に修正してみます。ありがとうございます！

**Comment by uhooi** [comment]
こちらこそお役に立てて嬉しいです…！
わからないことがあったらTwitterでも何でも聞いてください〜 👍 

ちなみにSwiftPMを使っているとのことですが、公式のREADMEにキャッシュの取得方法が書いてありますよ！↓
（私はSwiftPMを使ったことがないので、README以上のことはわからないですが）
https://github.com/actions/cache/blob/main/examples.md#swift---swift-package-manager

**Comment by naipaka** [comment]
@uhooi 
ありがとうございます…😭

SwiftPMもキャッシュ取得できたのですね！！ActionsのREADMEしっかりみてませんでした…
SwiftPMの方も対応してみます！本当感謝です🙇‍♂️
